Vile Rattus Cult
sprutton1/GrimdarkFutureBattlescribe pull request #90
Opened 2020-09-14 20:26 UTC by hhaddow

Just need someone to proofread it, everything seems to be there

2020-09-14 23:38 UTC, sprutton1 requested changes
Instead of the .catz file, can you submit the .cat file? The catz is a zip, so I can't review the text without pulling it down.

2020-09-14 23:38 UTC, sprutton1 commented on readme.md
> +|Vile Rattus Cult|v2.5|Awaiting Review|
Can you change this to "Done" instead as this will be what ends up in the repo once the change is merged?

2020-09-15 09:24 UTC, hhaddow commented
I've swapped it out for a catz file

2020-09-15 13:07 UTC, sprutton1 approved these changes

2020-09-15 13:07 UTC, sprutton1 commented on Vile Rattus Cult.cat
> +    <selectionEntry id="08a5-2fc9-18b4-e30a" name="Tripple Pistols" hidden="false" collective="false" import="true" type="upgrade">
Typo

2020-09-15 13:07 UTC, sprutton1 commented on Vile Rattus Cult.cat
> +        <profile id="e3f8-bb3d-c04a-b55d" name="Artillary Gun" hidden="false" typeId="a8fa-e9ce-c38a-c73e" typeName="Unit">
*Artillery

2020-09-15 13:08 UTC, sprutton1 reviewed
@Darguth I'm not sure if you want to pull this down and test out the file in BS. If not, I can merge it

2020-09-16 17:24 UTC, Darguth commented
@sprutton1 I didn't comb through it with a fine-tooth brush, but general review looks good. I don't have any problems merging this.

@hhaddow Welcome, glad to see another contributor!! A few minor notes for future work/iterations:
1. Rat Daemon was classified as a Monster: Heavy but I'd normally still put this under the Hero category because it has the special rule. I did this for things like Greater Daemons etc. in other lists.
2. Noticed you didn't include options for combined units. This can make the config a bit messier, but it's a feature that was requested often. I don't think it's make-or-break, but a nice-to-have.
3. When adding army-specific special rules to, I usually will include a reference link to the document. Just looks nicer on the final army list printout and lets people know where to lookup a rule if they have the OPR printouts handy. Not critical, just a mention.

Overall though it looks great. I like the grouping you did for upgrades to map more cleanly to the OPR lists, might lift that and borrow it for future work as well.

2020-09-16 17:28 UTC, merged

2020-09-16 18:12 UTC, hhaddow commented
@Darguth thanks, this was my first time working with the data side of Battlescribe so I'm glad that it made the grade, I might as well start on correcting some of the issues listed, also as Tunnel Leader is also a hero (on bike) should I give him the Hero class too

And feel free to lift the way I did the upgrades

2020-09-16 18:42 UTC, hhaddow commented
Found a couple of errors I missed, Upgrades F, Jetpacks is 15pts, should be 20pts, rat swarms had not been assigned their swarm attacks weapon, I'm just in the process of adding options for combined units.